// Constants
export const DEFAULT_ACTION = 'app/Auth/DEFAULT_ACTION'
export const UPDATE_FIELD = 'app/Auth/UPDATE_FIELD'
export const LOGIN_REQUEST = 'app/Auth/LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'app/Auth/LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_FAILURE = 'app/Auth/LOGIN_REQUEST_FAILURE'

export const SIGNUP_REQUEST = 'app/Auth/SIGNUP_REQUEST'
export const SIGNUP_REQUEST_SUCCESS = 'app/Auth/SIGNUP_REQUEST_SUCCESS'
export const SIGNUP_REQUEST_FAILURE = 'app/Auth/SIGNUP_REQUEST_FAILURE'

export const UPDATE_USER_REQUEST = 'app/Auth/UPDATE_USER_REQUEST'
export const UPDATE_USER_REQUEST_SUCCESS = 'app/Auth/UPDATE_USER_REQUEST_SUCCESS'
export const UPDATE_USER_REQUEST_FAILURE = 'app/Auth/UPDATE_USER_REQUEST_FAILURE'

export const CLEAR_SESSION_DATA = 'app/Auth/CLEAR_SESSION_DATA'

export const FETCH_USER = 'App/user/FETCH_USER'
export const FETCH_USER_SUCCESS = 'App/user/FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'App/user/FETCH_USER_FAILURE'

export const FETCH_USERS = 'App/user/FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'App/user/FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'App/user/FETCH_USERS_FAILURE'
